"""Generate audit prompts and routing views from repository-owned sources.

No reports, application configuration, models or historical data are modified.
Use --check in validation/CI; writing is explicit via --write.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
NOTICE = "<!-- GENERATED by scripts/sync_agent_instructions.py; edit the canonical source. -->\n"
WORKFLOW = Path(".claude/automation/audit-workflow.md")
PROMPTS = {
    "auditoria-claude-code-opus-5.md": ("Diagnóstico independiente — Claude", "review", "claude"),
    "auditoria-openai-astra.md": ("Diagnóstico independiente — OpenAI", "review", "openai"),
    "auditoria-consolidacion.md": ("Consolidación independiente", "consolidate", None),
    "corregir-auditoria.md": ("Remediación autorizada", "remediate", None),
    "verificar-remediacion.md": ("Verificación independiente", "verify", None),
}


def section(text: str, name: str) -> str:
    start = f"<!-- section: {name} -->"
    if text.count(start) != 1:
        raise ValueError(f"Expected one source section: {name}")
    tail = text.split(start, 1)[1]
    if "<!-- endsection -->" not in tail:
        raise ValueError(f"Unclosed source section: {name}")
    body = tail.split("<!-- endsection -->", 1)[0]
    if "<!-- section:" in body:
        raise ValueError(f"Nested/unclosed source section: {name}")
    return body.strip()


def replace_region(text: str, name: str, body: str) -> str:
    start, end = f"<!-- generated: {name} -->", f"<!-- endgenerated: {name} -->"
    if text.count(start) != 1 or text.count(end) != 1:
        raise ValueError(f"Expected one generated region: {name}")
    before, tail = text.split(start, 1)
    _, after = tail.split(end, 1)
    return before + start + "\n" + body.rstrip() + "\n" + end + after


def generated_files(root: Path = ROOT) -> dict[Path, str]:
    """Render the complete write set before changing any file."""
    source = (root / WORKFLOW).read_text(encoding="utf-8")
    common = section(source, "common")
    outputs = {}
    for name, (title, phase, auditor) in PROMPTS.items():
        context = (
            f"Auditor de esta ejecución: `{auditor}`. Preparar o unirse a la ronda\n"
            "según el contrato común. Durante el diagnóstico escribir su informe\n"
            f"y evidencia únicamente en `audit/latest/{auditor}/`. No leer al otro\n"
            "auditor ni la consolidación durante el diagnóstico principal.\n"
            if auditor else "Ejecutar únicamente la fase indicada en este documento.\n"
        )
        outputs[Path("audits/prompts") / name] = (
            NOTICE + f"# {title}\n\nFuente: `{WORKFLOW.as_posix()}`.\n\n"
            + context + "\n" + common + "\n\n" + section(source, phase) + "\n"
        )

    config = json.loads((root / ".claude/automation/model-routing.json").read_text(encoding="utf-8"))
    routes = sorted(config["routes"], key=lambda r: r["priority"], reverse=True)
    ids = [r["id"] for r in routes]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate route IDs")
    # `skill` es el playbook de la ruta (un directorio de .claude/skills/); null
    # cuando la ruta se cubre solo con su agente primario. Hasta el 2026-09-18 la
    # clave era `loop` (.claude/loops/*.md): los loops se fundieron en las skills
    # que los apuntaban, y los tres sin skill en su agente primario.
    for route in [*routes, config["default"]]:
        skill = route["skill"]
        if skill is not None and not (root / ".claude/skills" / skill / "SKILL.md").is_file():
            raise ValueError(f"Unknown skill: {skill}")
    table = ["| Ruta | Skill | Agente principal | Apoyo |", "|---|---|---|---|"]
    for route in [*routes, config["default"] | {"id": "default", "support_agents": []}]:
        skill = f"`{route['skill']}`" if route["skill"] else "—"
        table.append(
            f"| `{route['id']}` | {skill} | {route['primary_agent']} | "
            + ", ".join(route.get("support_agents", [])) + " |"
        )
    routing = (
        "Catálogo derivado de `.claude/automation/model-routing.json`. La política de\n"
        "modelos está en `MODEL_ROUTING.md`; esta tabla no cambia el modelo activo\n"
        "ni autoriza delegación, escrituras o ejecución de la skill.\n\n" + "\n".join(table)
    )
    for name in (".claude/ORCHESTRATOR.md", ".claude/automation/decision-engine.md"):
        path = Path(name)
        outputs[path] = replace_region((root / path).read_text(encoding="utf-8"), "routes", routing)

    quant = [r for r in routes if r["id"].startswith("quant-")]
    qtable = ["| Ruta | Skill |", "|---|---|"]
    qtable.extend(f"| `{r['id']}` | `{r['skill']}` |" for r in quant)
    router = Path(".claude/loops/quant/00-quant-operations-router.md")
    outputs[router] = replace_region((root / router).read_text(encoding="utf-8"), "quant-routes", "\n".join(qtable))

    # Los bloques de guardarrailes viven expandidos en cada skill operativa (y en
    # el router) para funcionar al cargarse aisladas; loop-guardrails.md es la
    # unica fuente. Una skill sin bloque no es operativa y se deja en paz.
    guards = (root / ".claude/automation/loop-guardrails.md").read_text(encoding="utf-8")
    carriers = [root / router, *sorted((root / ".claude/skills").glob("*/SKILL.md"))]
    for path in carriers:
        rel = path.relative_to(root)
        text = outputs.get(rel, path.read_text(encoding="utf-8"))
        for heading, name in (("Reglas comunes", "quant"), ("Common guardrails", "general")):
            pattern = rf"(## {heading}\n\n)(?:- [^\n]*\n)+"
            replacement = section(guards, name) + "\n"
            text, count = re.subn(pattern, lambda m, r=replacement: m[1] + r, text)
            if count > 1:
                raise ValueError(f"Ambiguous guardrail block ({heading}): {rel}")
        outputs[rel] = text
    return outputs


def sync(root: Path = ROOT, *, write: bool = False) -> list[Path]:
    outputs = generated_files(root)
    stale = [path for path, text in outputs.items()
             if not (root / path).exists()
             or (root / path).read_text(encoding="utf-8") != text]
    if write:
        for path in stale:
            (root / path).write_text(outputs[path], encoding="utf-8", newline="\n")
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale = sync(write=args.write)
    for path in stale:
        print(f"{'Updated' if args.write else 'Out of sync'}: {path.as_posix()}")
    if not stale:
        print("Agent instructions: synchronized")
    return 1 if stale and not args.write else 0


if __name__ == "__main__":
    raise SystemExit(main())
